"""
Test Data Management Models

Core data models for test data management system.
"""

import uuid
from datetime import datetime, timezone
from typing import Dict, List, Optional, Any, Union
from enum import Enum
from dataclasses import dataclass, field


class DataScope(str, Enum):
    """Data scope enumeration."""
    GLOBAL = "global"           # Available to all tests
    SUITE = "suite"             # Available to specific test suite
    CASE = "case"               # Available to specific test case
    EXECUTION = "execution"     # Available to specific execution session
    TEMPORARY = "temporary"     # Temporary data, auto-cleanup


class DataType(str, Enum):
    """Data type enumeration."""
    PERSON = "person"           # Personal information
    COMPANY = "company"         # Company/organization data
    FINANCIAL = "financial"     # Financial data (cards, accounts)
    PRODUCT = "product"         # Product/inventory data
    FORM = "form"               # Web form data
    API = "api"                 # API request/response data
    CUSTOM = "custom"           # Custom data structures


class DataSource(str, Enum):
    """Data source enumeration."""
    GENERATED = "generated"     # Generated by data generators
    DATABASE = "database"       # From database queries
    FILE = "file"               # From files (CSV, JSON, etc.)
    API = "api"                 # From API calls
    MANUAL = "manual"           # Manually created
    IMPORTED = "imported"       # Imported from external sources


class MaskingStrategy(str, Enum):
    """Data masking strategy."""
    NONE = "none"               # No masking
    PARTIAL = "partial"         # Partial masking (e.g., ****1234)
    FULL = "full"               # Full replacement
    HASH = "hash"               # Hash-based masking
    TOKENIZE = "tokenize"       # Tokenization
    ENCRYPT = "encrypt"         # Encryption


@dataclass
class DataMaskingRule:
    """Data masking rule definition."""
    field_name: str
    strategy: MaskingStrategy
    pattern: Optional[str] = None
    replacement: Optional[str] = None
    preserve_format: bool = True
    preserve_length: bool = True


@dataclass
class TestDataRecord:
    """Individual test data record."""
    
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    data: Dict[str, Any] = field(default_factory=dict)
    
    # Metadata
    data_type: DataType = DataType.CUSTOM
    source: DataSource = DataSource.MANUAL
    tags: List[str] = field(default_factory=list)
    labels: Dict[str, str] = field(default_factory=dict)
    
    # Masking
    is_masked: bool = False
    masking_rules: List[DataMaskingRule] = field(default_factory=list)
    original_data_hash: Optional[str] = None
    
    # Usage tracking
    usage_count: int = 0
    last_used: Optional[datetime] = None
    
    # Audit fields
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    created_by: str = "system"
    
    def get_field(self, field_name: str, default: Any = None) -> Any:
        """Get a field value from the data."""
        return self.data.get(field_name, default)
    
    def set_field(self, field_name: str, value: Any) -> None:
        """Set a field value in the data."""
        self.data[field_name] = value
        self.updated_at = datetime.now(timezone.utc)
    
    def mark_used(self) -> None:
        """Mark record as used."""
        self.usage_count += 1
        self.last_used = datetime.now(timezone.utc)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "id": self.id,
            "data": self.data,
            "data_type": self.data_type.value,
            "source": self.source.value,
            "tags": self.tags,
            "labels": self.labels,
            "is_masked": self.is_masked,
            "masking_rules": [
                {
                    "field_name": rule.field_name,
                    "strategy": rule.strategy.value,
                    "pattern": rule.pattern,
                    "replacement": rule.replacement,
                    "preserve_format": rule.preserve_format,
                    "preserve_length": rule.preserve_length
                }
                for rule in self.masking_rules
            ],
            "original_data_hash": self.original_data_hash,
            "usage_count": self.usage_count,
            "last_used": self.last_used.isoformat() if self.last_used else None,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
            "created_by": self.created_by
        }


@dataclass
class TestDataSet:
    """Collection of test data records."""
    
    id: str = field(default_factory=lambda: str(uuid.uuid4()))
    name: str = ""
    description: str = ""
    
    # Data organization
    records: List[TestDataRecord] = field(default_factory=list)
    schema: Dict[str, Any] = field(default_factory=dict)  # Data schema definition
    
    # Scope and access
    scope: DataScope = DataScope.GLOBAL
    environment: str = "default"
    
    # Configuration
    data_type: DataType = DataType.CUSTOM
    source: DataSource = DataSource.MANUAL
    auto_refresh: bool = False
    refresh_interval: int = 3600  # seconds
    
    # Data management
    max_records: Optional[int] = None
    auto_cleanup: bool = False
    retention_days: Optional[int] = None
    
    # Masking configuration
    masking_enabled: bool = False
    masking_rules: List[DataMaskingRule] = field(default_factory=list)
    
    # Metadata
    tags: List[str] = field(default_factory=list)
    labels: Dict[str, str] = field(default_factory=dict)
    
    # Statistics
    total_records: int = 0
    used_records: int = 0
    last_refresh: Optional[datetime] = None
    
    # Audit fields
    created_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    updated_at: datetime = field(default_factory=lambda: datetime.now(timezone.utc))
    created_by: str = "system"
    version: int = 1
    
    def add_record(self, record: TestDataRecord) -> None:
        """Add a record to the dataset."""
        self.records.append(record)
        self.total_records = len(self.records)
        self.updated_at = datetime.now(timezone.utc)
    
    def remove_record(self, record_id: str) -> bool:
        """Remove a record from the dataset."""
        for i, record in enumerate(self.records):
            if record.id == record_id:
                self.records.pop(i)
                self.total_records = len(self.records)
                self.updated_at = datetime.now(timezone.utc)
                return True
        return False
    
    def get_record(self, record_id: str) -> Optional[TestDataRecord]:
        """Get a record by ID."""
        return next((record for record in self.records if record.id == record_id), None)
    
    def get_records_by_tags(self, tags: List[str]) -> List[TestDataRecord]:
        """Get records that have any of the specified tags."""
        return [
            record for record in self.records
            if any(tag in record.tags for tag in tags)
        ]
    
    def get_unused_records(self) -> List[TestDataRecord]:
        """Get records that haven't been used."""
        return [record for record in self.records if record.usage_count == 0]
    
    def get_random_record(self, used: bool = False) -> Optional[TestDataRecord]:
        """Get a random record from the dataset."""
        import random
        
        if used:
            available_records = self.records
        else:
            available_records = self.get_unused_records()
        
        if not available_records:
            return None
        
        record = random.choice(available_records)
        record.mark_used()
        self.used_records = sum(1 for r in self.records if r.usage_count > 0)
        
        return record
    
    def get_record_by_criteria(self, criteria: Dict[str, Any]) -> Optional[TestDataRecord]:
        """Get a record that matches the specified criteria."""
        for record in self.records:
            if all(
                record.get_field(key) == value
                for key, value in criteria.items()
            ):
                record.mark_used()
                self.used_records = sum(1 for r in self.records if r.usage_count > 0)
                return record
        return None
    
    def reset_usage(self) -> None:
        """Reset usage statistics for all records."""
        for record in self.records:
            record.usage_count = 0
            record.last_used = None
        self.used_records = 0
        self.updated_at = datetime.now(timezone.utc)
    
    def apply_masking(self) -> None:
        """Apply masking rules to all records."""
        if not self.masking_enabled or not self.masking_rules:
            return
        
        from .masking import DataMasker
        masker = DataMasker()
        
        for record in self.records:
            if not record.is_masked:
                masker.mask_record(record, self.masking_rules)
        
        self.updated_at = datetime.now(timezone.utc)
    
    def get_statistics(self) -> Dict[str, Any]:
        """Get dataset statistics."""
        return {
            "total_records": self.total_records,
            "used_records": self.used_records,
            "unused_records": self.total_records - self.used_records,
            "usage_rate": self.used_records / self.total_records if self.total_records > 0 else 0,
            "data_type": self.data_type.value,
            "source": self.source.value,
            "scope": self.scope.value,
            "environment": self.environment,
            "masking_enabled": self.masking_enabled,
            "auto_refresh": self.auto_refresh,
            "last_refresh": self.last_refresh.isoformat() if self.last_refresh else None,
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
            "version": self.version
        }
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert to dictionary."""
        return {
            "id": self.id,
            "name": self.name,
            "description": self.description,
            "records": [record.to_dict() for record in self.records],
            "schema": self.schema,
            "scope": self.scope.value,
            "environment": self.environment,
            "data_type": self.data_type.value,
            "source": self.source.value,
            "auto_refresh": self.auto_refresh,
            "refresh_interval": self.refresh_interval,
            "max_records": self.max_records,
            "auto_cleanup": self.auto_cleanup,
            "retention_days": self.retention_days,
            "masking_enabled": self.masking_enabled,
            "masking_rules": [
                {
                    "field_name": rule.field_name,
                    "strategy": rule.strategy.value,
                    "pattern": rule.pattern,
                    "replacement": rule.replacement,
                    "preserve_format": rule.preserve_format,
                    "preserve_length": rule.preserve_length
                }
                for rule in self.masking_rules
            ],
            "tags": self.tags,
            "labels": self.labels,
            "statistics": self.get_statistics(),
            "created_at": self.created_at.isoformat(),
            "updated_at": self.updated_at.isoformat(),
            "created_by": self.created_by,
            "version": self.version
        }
